# Generated by Django 6.0.2 on 2026-02-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('entry_fee', models.PositiveIntegerField(default=0)),
                ('avg_food', models.PositiveIntegerField(default=0)),
                ('duration_min', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price_tier', models.CharField(max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('vibes', models.JSONField(blank=True, default=list)),
                ('popularity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.neighbourhood')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
