# Generated by Django 6.0.2 on 2026-02-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='Matatu', max_length=50)),
                ('fare', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='trips.neighbourhood')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='trips.neighbourhood')),
            ],
            options={
                'ordering': ['origin__name', 'destination__name'],
                'unique_together': {('origin', 'destination')},
            },
        ),
    ]
